### ISSUE TITLE
bug: Provide a field name transformer for columns which are to be selected

### ISSUE THREAD

**Issue by Lewenhaupt** [ardsh/slonik-trpc#44]
We're using https://github.com/gajus/slonik-interceptor-field-name-transformation with slonik in order to camelCase all column names that are returned. This means all our zod schemas have camelCase keys. This in turn leads to  the typing in `makeQueryLoader` to suggest the camelCase keys in the typing of the `select` parameter in `getQuery` and `load` and throwing tsErrors if one uses the snake case variants. I think it would make sense to have the ability to either toggle it or provide a plugin that would ensure that the column names are converted before the query is executed.
Unfortunately Slonik does not seem to provide a way to do this since all that can be retrieved pre-query is the raw query and I'd rather not try to figure out what is a column name and what is some nested jsonb etc.

After also testing live it appears my workaround is not working. Because if select receives a column name that is not in the known keys of the parser it will not be passed into the query :/

**Comment by ardsh** [comment]
I understand. Unfortunately the query engine relies on the object keys from the zod schema being the same name as the SQL columns right now, and there's no easy way to bypass this that I can see (short of using something else besides a slonik interceptor to change the column names to camel case).

However I think this can be solved using plugins like you suggested, but not in the current release, since plugins don't yet allow you to transform column names like that.

**Comment by Lewenhaupt** [comment]
Are you open to contributions? I guess one could extend the plugins to allow more functionality right?

**Comment by ardsh** [comment]
@Lewenhaupt Yes I'm open to contributions, though so far I'm maintaining this solo but all contributions are welcome.

After a bit more thought though, this doesn't quite fit the plugins use-case, it's a more narrow use case.
[I've now added an option](https://github.com/ardsh/slonik-trpc/commit/c79cd978b5d618d8d70400ddcba51e1fd359ea82) to transform the SQL column names, so you can transform them back to snake case before they're used to create the query.

This should work in the new 0.14.2 release, I believe the test example shows your exact use case, if you specify a snakeCase convertor (I know there are cases where this may not always be the case, but in those cases you'd just have to provide some more complicated function for mapping the fields back to their SQL column names)

```
options: {
    transformColumns: column => snakeCase(column),
},
```

**Comment by Lewenhaupt** [comment]
@ardsh Awesome! :D I'll try it out straight away!
